"""
YAML config parsing and op_db filtering for the OOT PyTorch test framework.

Responsibilities:
  - load_yaml_config: read YAML and return validated OOTTestConfig
  - resolve_rel_path: expand ${PYTORCH} / ${TORCH_SPYRE} tokens
  - resolve_current_file: match a YAML file entry against cwd
  - filter_op_db: monkey-patch pytorch op_db lists to supported_ops subset
"""

import os
import sys
import warnings
from pathlib import Path
from typing import Dict, Optional

import yaml

from spyre_test_constants import REL_PATH_TOKENS
from spyre_test_config_models import FileEntry, OOTTestConfig, SupportedOpConfig


# ---------------------------------------------------------------------------
# YAML loading
# ---------------------------------------------------------------------------


def load_yaml_config(path: str) -> OOTTestConfig:
    """Load YAML and return a validated OOTTestConfig.

    Pydantic validates structure, field types, dtype strings, mode values,
    and test id format automatically.

    Raises:
        FileNotFoundError: if the YAML file does not exist.
        pydantic.ValidationError: if the YAML structure is invalid.
    """
    config_path = Path(path)
    if not config_path.exists():
        raise FileNotFoundError(f"OOT test config file not found: {config_path}")

    with open(config_path) as f:
        raw = yaml.safe_load(f) or {}

    return OOTTestConfig.model_validate(raw)


# ---------------------------------------------------------------------------
# Path resolution
# ---------------------------------------------------------------------------


def resolve_rel_path(path: str) -> str:
    """Expand ${PYTORCH} and ${TORCH_SPYRE} tokens using env vars."""
    for token, env_var in REL_PATH_TOKENS:
        if token in path:
            root = os.environ.get(env_var)
            if not root:
                raise EnvironmentError(
                    f"path contains {token!r} but ${env_var} is not set."
                )
            path = path.replace(token, root)
    return path


# ---------------------------------------------------------------------------
# Debug helper
# ---------------------------------------------------------------------------


def _debug(msg: str) -> None:
    os.write(2, f"[DEBUG] resolve_current_file: {msg}\n".encode())


# Suffix appended to wrapper files generated by run_test.sh for classes that
# were not originally passed to instantiate_device_type_tests().
_OOT_WRAPPER_SUFFIX = "__oot_wrapper"


def _unwrap_oot_path(path: str) -> str:
    """If *path* points to an auto-generated OOT wrapper, return the path of
    the original upstream file it wraps.

    run_test.sh names wrappers as ``<original_stem>__oot_wrapper.py`` and
    places them in the same directory as the original.  Stripping that suffix
    recovers the original path so ``resolve_current_file`` can match it
    against the YAML entries unchanged.

    If *path* does not end with the wrapper suffix the function returns it
    unchanged.
    """
    p = Path(path)
    if p.stem.endswith(_OOT_WRAPPER_SUFFIX):
        original_stem = p.stem[: -len(_OOT_WRAPPER_SUFFIX)]
        return str(p.with_name(original_stem + p.suffix))
    return path


# ---------------------------------------------------------------------------
# Current file resolution
# ---------------------------------------------------------------------------

# Environment variable set by run_test.sh before every pytest invocation
# (both normal and xdist fallback).
# It is set unconditionally by the orchestrator and survives into
# xdist worker processes via inherited environment, unlike sys.argv (empty
# in workers) and PYTEST_CURRENT_TEST (only set during test *execution*,
# not during the *collection* phase when resolve_current_file is called).
_ENV_SPYRE_TEST_FILE = "SPYRE_TEST_FILE"


def _resolve_candidate(raw: str, cwd: Path) -> Optional[str]:
    """Resolve *raw* to an absolute path and return it if it exists, else None."""
    candidate = Path(raw)
    resolved = (
        (cwd / candidate).resolve()
        if not candidate.is_absolute()
        else candidate.resolve()
    )
    return str(resolved) if resolved.exists() else None


def _find_test_file_from_env(cwd: Path) -> Optional[str]:
    """Return the original (non-wrapper) test file path from SPYRE_TEST_FILE.

    run_test.sh exports SPYRE_TEST_FILE=<absolute path to wrapper or original>
    immediately before each pytest invocation.  Child processes — including
    xdist worker subprocesses — inherit it via the environment, so it is
    present during both *collection* and *execution*.

    The OOT wrapper suffix is stripped here so the return value always
    points to the original upstream file that matches the YAML entry.

    Returns the resolved absolute path string, or None if unset / not found.
    """
    value = os.environ.get(_ENV_SPYRE_TEST_FILE, "")
    if not value:
        return None
    # Unwrap before resolving so the path we check on disk is the original file.
    unwrapped = _unwrap_oot_path(value)
    return _resolve_candidate(unwrapped, cwd)


def _find_test_file_from_argv(cwd: Path) -> Optional[str]:
    """Extract the test file path from sys.argv.

    Handles two argv shapes:
      1. Normal pytest run:  argv = ['pytest', 'test_foo.py', ...]
         The test file appears as a plain .py argument.

      2. xdist node-ID args: argv = ['pytest', 'test_foo.py::Class::method', ...]
         The .py path is the prefix before the first '::'.

    sys.argv[1:] is empty in xdist workers dispatched via internal channels,
    so this source falls through to the env-var sources in that case.

    Returns the resolved absolute path string, or None if not found.
    """
    for arg in sys.argv[1:]:
        if arg.startswith("-"):
            continue
        file_part = arg.split("::")[0]
        if not file_part.endswith(".py"):
            continue
        result = _resolve_candidate(file_part, cwd)
        if result is not None:
            return result
    return None


def _find_test_file_from_pytest_current_test(cwd: Path) -> Optional[str]:
    """Extract the test file path from the PYTEST_CURRENT_TEST environment variable.

    pytest and xdist set PYTEST_CURRENT_TEST to the current node ID, e.g.:

        tests/models/test_model_ops_v2.py::TestClass::test_method (call)

    This env var is only set during test *execution*, not during
    *collection*.  resolve_current_file is called from instantiate_test()
    which runs at collection time, so this is a last-resort fallback for
    cases where SPYRE_TEST_FILE is not set (e.g. direct pytest invocations
    outside of run_test.sh during an ongoing test run).

    Returns the resolved absolute path string, or None if not set / not found.
    """
    value = os.environ.get("PYTEST_CURRENT_TEST", "")
    if not value:
        return None
    node_id = value.split(" ")[0]  # strip " (call)" / " (setup)" annotation
    file_part = node_id.split("::")[0]
    if not file_part.endswith(".py"):
        return None
    return _resolve_candidate(file_part, cwd)


def resolve_current_file(config: OOTTestConfig, config_path: str) -> FileEntry:
    """Match a YAML file entry against the file pytest is currently running.

    Source priority for determining the current test file:

    1. SPYRE_TEST_FILE env var — exported by run_test.sh before every pytest
       invocation (normal and xdist fallback alike).  Inherited by all child
       processes including xdist workers.  Available during both collection
       and execution, making it the only source that works reliably in all
       scenarios.  The OOT wrapper suffix is stripped automatically.

    2. sys.argv — works for normal pytest runs and for xdist node-ID args,
       but is empty in xdist workers dispatched via internal channels.

    3. PYTEST_CURRENT_TEST env var — only set during test execution, not
       collection.  Last-resort fallback for direct pytest invocations that
       bypass run_test.sh.

    Raises EnvironmentError if no source yields a match.
    """

    cwd = Path(os.getcwd()).resolve()

    # --- Source 1: SPYRE_TEST_FILE (set by run_test.sh ---
    current_test_file = _find_test_file_from_env(cwd)
    if current_test_file is not None:
        _debug(f"resolved from {_ENV_SPYRE_TEST_FILE}: {current_test_file!r}")

    # --- Source 2: sys.argv ---
    if current_test_file is None:
        current_test_file = _find_test_file_from_argv(cwd)

    # --- Source 3: PYTEST_CURRENT_TEST (execution-time only; fallback resort) ---
    if current_test_file is None:
        current_test_file = _find_test_file_from_pytest_current_test(cwd)
        if current_test_file is not None:
            _debug(f"resolved from PYTEST_CURRENT_TEST: {current_test_file!r}")

    if current_test_file is None:
        raise EnvironmentError(
            f"Could not determine the test file being run.\n"
            f"  {_ENV_SPYRE_TEST_FILE}={os.environ.get(_ENV_SPYRE_TEST_FILE, '')!r}\n"
            f"  sys.argv[1:]={sys.argv[1:]!r}\n"
            f"  PYTEST_CURRENT_TEST={os.environ.get('PYTEST_CURRENT_TEST', '')!r}\n"
            f"Make sure run_test.sh exports {_ENV_SPYRE_TEST_FILE} before invoking pytest, "
            f"or invoke pytest with an explicit test file, e.g. `pytest test_ops.py`."
        )

    # Source 1 already strips the wrapper suffix; strip here for sources 2 & 3.
    lookup_file = _unwrap_oot_path(current_test_file)
    if lookup_file != current_test_file:
        _debug(
            f"OOT wrapper detected: {current_test_file!r} -> resolving as {lookup_file!r}"
        )

    for file_entry in config.files:
        entry_resolved = str(Path(resolve_rel_path(file_entry.path)).resolve())
        _debug(
            f"entry: {file_entry.path!r} -> {entry_resolved!r} match={entry_resolved == lookup_file}"
        )
        if entry_resolved == lookup_file:
            return file_entry

    raise EnvironmentError(
        f"No rel_path in {config_path!r} matches the test file being run "
        f"({current_test_file!r}).\n"
        f"sys.argv={sys.argv!r}\n"
        f"Available entries:\n"
        + "\n".join(f"  {resolve_rel_path(f.path)}" for f in config.files)
    )


def apply_op_config_overrides(
    op_configs: Dict[str, "SupportedOpConfig"],
) -> None:
    """Apply per-op attribute overrides (dtypes, precision) to OpInfo objects.

    Mutates OpInfo attributes in-place on op_db entries. Because @ops reads
    op.dtypes / op.atol etc. from the OpInfo object at parametrize time,
    these mutations propagate to test generation even though @ops.op_list
    was copied at decoration time.

    Op filtering for test generation is handled separately by
    _OOTOpListPatcher -- this function only handles attribute overrides.

    Precision is now per (op, dtype) rather than per op. Since OpInfo stores
    a single atol/rtol, we apply the precision from the first dtype entry
    that has a precision override. Per-dtype precision at test runtime is
    handled separately via cls.precision in instantiate_test.
    """
    import torch.testing._internal.common_methods_invocations as _cmi

    op_db = getattr(_cmi, "op_db", [])
    op_info_by_name = {op.name: op for op in op_db}

    for op_name, cfg in op_configs.items():
        op_info = op_info_by_name.get(op_name)
        if op_info is None:
            warnings.warn(
                f"apply_op_config_overrides: op {op_name!r} not found in op_db.",
                stacklevel=2,
            )
            continue

        # Override dtypes if specified at op level.
        # Bypass OpInfo.__setattr__ validation by writing to __dict__ directly
        # with a frozenset -- frozenset supports set operations (.intersection
        # etc.) that upstream _parametrize_test relies on, whereas
        # _dispatch_dtypes does not.
        resolved_dtypes = cfg.resolved_dtypes()
        if resolved_dtypes is not None:
            dtype_frozenset = frozenset(resolved_dtypes)
            op_info.__dict__["dtypes"] = dtype_frozenset

            # also set dtypesIfPrivateUse1 so supported_dtypes(device_type)
            # returns the correct set for the privateuse1 device path.
            # _parametrize_test calls op.supported_dtypes("privateuse1") which
            # checks dtypesIfPrivateUse1 before falling back to dtypes.
            # Without this, our dtypes override is bypassed for privateuse1 variants.
            op_info.__dict__["dtypesIfPrivateUse1"] = dtype_frozenset

        for dtype_cfg in cfg.dtypes:
            if dtype_cfg.precision is not None:
                if dtype_cfg.precision.atol is not None:
                    op_info.atol = dtype_cfg.precision.atol  # type: ignore[attr-defined]
                if dtype_cfg.precision.rtol is not None:
                    op_info.rtol = dtype_cfg.precision.rtol  # type: ignore[attr-defined]
                break  # apply first found, stop — OpInfo has one atol/rtol
